import { Button, Form, Input } from "antd";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React, { useState } from "react";
import CostumerAPI from "../src/api/customers";
import styles from "../styles/login.module.css";
const Login = () => {
  const [state, setState] = useState({
    email: "akun12@mig.id",
    password: "BA8A9E03",
  });
  const onFinish = (values: any) => {
    CostumerAPI.login(state);
  };

  const handleChange = (e: any): void => {
    const { name, value } = e.target as HTMLInputElement;
    setState({
      ...state,
      [name]: value,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Login Mitramas Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Please Login Down Below</h1>
      <Form
        name="Login"
        labelCol={{ span: 6 }}
        initialValues={{ remember: true }}
        onFinish={onFinish}
        autoComplete="off"
      >
        <Form.Item
          label="Email"
          name="email"
          initialValue={state.email}
          rules={[{ required: true, message: "Please input your username!" }]}
        >
          <Input
            // type={"email"}
            name="email"
            placeholder="Email"
            onChange={(e: any) => handleChange(e)}
            style={{ width: 350 }}
          />
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          initialValue={state.password}
          rules={[{ required: true, message: "Please input your password!" }]}
        >
          <Input.Password
            placeholder="Password"
            hidden={false}
            style={{ width: 350 }}
          />
        </Form.Item>

        <Form.Item wrapperCol={{ offset: 6, span: 16 }}>
          <Button htmlType="submit">Submit</Button>
        </Form.Item>
      </Form>
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const { token } = req.cookies;
  if (token) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  return {
    props: {},
  };
};
export default Login;
